---
title: "Group 4 SIR Model"
author: "Group 4 members"
date: "2024-09-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




# Load the necessary libraries

```{r}

library(deSolve)
library(ggplot2)
library(reshape2)
library(MASS)

```





############################################################################################################
# Let's consider the fact that infected people die



```{r}

# Define base parameters 
base_params <- c(
  beta = 0.25,         # Transmission rate 
  gamma_I = 0.7,        # Recovery rate for those who were infectious and remained on the general population
  sigma = 0.1,            #Detection rate
  gamma_Id = 1.4,        # Recovery rate for thise who were detected
  rho_I = 0.0049,           # Mortality rate for the infected people in the community
  rho_Id = 0.00455          # Mortality rate for the infected people that were detected and isolated
  
)

# Define initial state
initial_state <- c(
  S = 105e3,        # Susceptible
  I = 20,         # Infectious
  Id = 8,         #Detected population
  R = 0,         # Recovered
  D = 0         #Dead
)

# Define the time sequence for 37 weeks
times <- seq(0, 37, by = 1)

# Function to run the model
run_model <- function(params) {
  model <- function(t, state, parameters) {
    with(as.list(c(state, parameters)), {
      N <- S + I + Id + R + D
      dS <- -beta * S * I/N
      dI <- beta * S * I/N - gamma_I * I - sigma*I - rho_I*I
      dId <- sigma*I - gamma_Id *Id - rho_Id*Id
      dR <- gamma_I * I + gamma_Id *Id
      dD <- rho_I*I + rho_Id*Id
      
      return(list(c(dS, dI, dId, dR, dD)))
    })
  }
  
  # Run the model
  output <- ode(y = initial_state, times = times, func = model, parms = params)
  
  return(as.data.frame(output))
}

# Run the model
output <- run_model(base_params)

output


# Rename columns for clarity
colnames(output) <- c("time", "Susceptible", "Infectious","Detected", "Recovered","Dead")

# Plot the results
ggplot(data = output, aes(x = time)) +
  geom_line(aes(y = Susceptible, color = "Susceptible"), size = 1) +
  geom_line(aes(y = Infectious, color = "Infectious"), size = 1) +
  geom_line(aes(y = Detected, color = "Detected"), size = 1) +
  geom_line(aes(y = Recovered, color = "Recovered"), size = 1) +
  geom_line(aes(y = Dead, color = "Dead"), size = 1) +
  labs(title = "SIR Model Simulation", x = "Days", y = "Population") +
  scale_color_manual("", 
                     breaks = c("Susceptible", "Infectious", "Detected","Recovered","Dead"),
                     values = c("blue", "red","brown", "green","black")) +
  theme_minimal() +
  theme(legend.position = "bottom")

```








